import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Slider from 'react-slick'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Card from '../componate/card'
import Link from 'next/link'
import Quiclink from '../componate/link'



export default function Home() {
     const settings = {
          infinite: true,
          dots: true,
          slidesToShow: 1,
          slidesToScroll: 1,
          lazyLoad: true,
          autoplay: true,
          autoplaySpeed: 1000,


     };
     const settings1 = {
          infinite: true,
          dots: true,
          slidesToShow: 1,
          slidesToScroll: 1,
          lazyLoad: true,
          autoplay: true,
          autoplaySpeed: 1000,


     };
     return (

          <>
               <div className='container'>


                    <section >
                         <Head>
                              <title>Create Next App</title>
                              <meta name="description" content="Generated by create next app" />
                              <link rel="icon" href="/favicon.ico" />
                         </Head>
                         <main className={styles.main}>
                              <div class="carousel-inner">
                                   <Slider {...settings}>
                                        <div className="carousel-item">
                                             <img src="img/img3.jpg" className="d-block w-100" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                             <img src="/img/hero.jpg" className="d-block w-100" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                             <img src="/img/51457.jpg" className="d-block w-100" alt="..." />
                                        </div>
                                   </Slider>
                              </div>
                         </main>
                    </section>
                    <section>
                         <div className="blog-container">
                              <h2 className=''>latest blog</h2>
                              <div className="blog-body">
                                   <div className="card main-blog-card">
                                        <div id="imgbox2">
                                             <img src="/img/ch2.jpg" id='img-blog' alt="..." />
                                        </div>
                                        <div className="blog-contant">
                                             <h5 className='card-title'>date 20 20</h5>
                                             <a href="#contact" className="card-text">lates news lorem isupm doler</a>
                                             <p className="text-primary"><Link href={"/"} ><a>Read More</a></Link></p>
                                        </div>
                                   </div>
                                   <div className=" d-flex">
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/7cNRozs.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Geysers Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Russia</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/CS59IJZ.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Khumbu Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Nepal</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>

                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div> <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                        <div className="col-md-4">
                                             <div className="content"> <a href="#">
                                                  <div className="content-overlay"></div> <img className="content-image" src="https://i.imgur.com/LITAKvq.jpg" />
                                                  <div className="content-details fadeIn-bottom">
                                                       <h3 className="content-title">Waipi&rsquo;o Valley Hotel</h3>
                                                       <p className="content-text"><i className="fa fa-map-marker"></i> Hawaii</p>
                                                  </div>
                                             </a> </div>
                                        </div>
                                   </div>
                              </div>

                         </div>
                    </section>

                    <section>
                         <div className="fixed-bg">
                              <div className='link-box'>
                                   <ul className='wrp-link'>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li><li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>
                                        <li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li><li className='text-link '><Link href={"/"} ><a className="font-weight-bold text-primrey">lates news lorem isupm doler</a></Link></li>

                                   </ul>
                                   <button type="button" className="btn btn-primrey link-btn d-block">
                                            <Link href="/series"><a >More View </a></Link>
                                        </button>

                              </div>

                         </div>
                    </section>

                    <Card data="Faimly Story" />
                    <Card data="Kids Story" />
                    <section>
                         <Quiclink />
                    </section>
               </div>
          </>
     )
}